name: Scheduled Task

on:
  schedule:
    - cron: '30 0 * * *'   # 6:00 AM IST
    - cron: '30 16 * * *'  # 10:00 PM IST

jobs:
  run-scheduled-task:
    runs-on: ubuntu-latest
    if: |
      contains('Tue Wed Fri Sat Sun', format('ddd', github.event.schedule))
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run your script or command
        run: |
          echo "Running scheduled job on $(date)"
